name: Build and push Docker images

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    strategy:
      matrix:
        include:
          - toolchain: gcc
            version: 8
          - toolchain: gcc
            version: 9
          - toolchain: gcc
            version: 12
          - toolchain: gcc
            version: 9-centos
          - toolchain: gcc
            version: 13
          - toolchain: gcc
            version: 13-alpine
          - toolchain: gcc
            version: 14
          - toolchain: gcc
            version: 14-rhel-ubi9
          - toolchain: clang
            version: 15
          - toolchain: clang
            version: 17
          - toolchain: clang
            version: 18
          - toolchain: clang
            version: 19
          - toolchain: mojo

    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: ${{ github.repository }}:${{ matrix.toolchain }}${{ matrix.version }}
      IMAGE_ROOT: ${{ github.workspace }}/${{ matrix.toolchain }}/${{ matrix.version }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Build Docker image
        # working-directory: ${{ env.IMAGE_ROOT }}
        run: |
          pwd
          cd $GITHUB_WORKSPACE
          pwd
          ls -ltrah
          cd ${{ matrix.toolchain }}/${{ matrix.version }}
          pwd
          ls -ltrah
          docker build -t ${REGISTRY}/${IMAGE_NAME} -f Dockerfile .
      
      - name: Log in to the Container registry
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Extract metadata (tags, labels) for Docker
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: docker/metadata-action@369eb591f429131d6889c46b94e711f089e6ca96
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Push Docker image
        if: ${{ github.ref == 'refs/heads/main' }}
        id: push
        run: |
          docker push ${REGISTRY}/${IMAGE_NAME}

      # Fixme: the 'build' step doesn't output the digest at the moment
      # - name: Generate artifact attestation
      #   if: ${{ github.ref == 'refs/heads/main' }}
      #   uses: actions/attest-build-provenance@7668571508540a607bdfd90a87a560489fe372eb
      #   with:
      #     subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      #     subject-digest: ${{ steps.push.outputs.digest }}
      #     push-to-registry: true
